### ISSUE TITLE
Additional report formatting options for scan results

### ISSUE THREAD

**Issue by niapoor** [cisagov/mesa-toolkit#16]
# 💡 Summary #

This work allows for additional forms of report formatting, namely PDF and JSON.

## Motivation and Context ##

Currently the only output format is HTML. This can be inconvenient for users who want to share reports of the mesa tool with others. Additionally, it can be difficult for analysts to process this data. Including options for pdf and json report formats could help to remedy these issues.

## Implementation Notes ##

* Use this by selecting either the "Download Report" or "Download JSON Report" buttons in the mesa gui and observing the associated report files.
* This issue is connected to the following issue in the mesa gui: https://github.com/cisagov/mesa-gui/issues/10

## Acceptance criteria ##

How do we know when this work is done?

- [ ] The report pdf is created in the report directory of the output zip file when pressing the "Download Report" button in the mesa gui. Currently, all scans must be run to produce this output. After html reporting can be done without all scans being run, it should be easy to adapt to the pdf output.
- [ ] The report json is created in the json directory of the output zip file when pressing the "Download JSON Report" button in the mesa gui. It should be noted that not all output data is currently included in the generated JSON file. It should be able to withstand missing files and scans without error, however it will not produce meaningful output unless all scans are completed.
- [ ] The report html and report pdf can be removed from the report directory and still display the CISA logo image.

**Comment by m1j09830** [comment]
This issue was satisfied by #17
