### ISSUE TITLE
Vulnerability scan does not properly show as completed when ran from GUI

### ISSUE THREAD

**Issue by m1j09830** [cisagov/mesa-toolkit#7]
# 🐛 Summary #

Vulnerability scan does not properly show as completed when ran from GUI. This is due to a missing variable that writes the .complete file after the scan has finished running. 

## To reproduce ##

1. Build the mesa-ops.ova using the mesa-packer repo (https://github.com/cisagov/mesa-packer.git)
2. Load the vm into VMware fusion
3. Run the All Checks option from the GUI after supplying the scope
4. Verify that the vulnerability scans are running on the backend as intended (`sudo journalctl -fu mesa.service`)
5. Notice the vulnerability scans are showing at `Not Started` after they have successfully completed in the GUI

## Expected behavior ##

The Vulnerability Scans should have shown as `Complete` after the scans successfully completed

**Comment by coffeegist** [comment]
Closed by #8
